#授权服务配置（spring-security-oauth2 过期不完善的）
authorization-server:
  hostname: localhost
  port: 8510
  issuerUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}
  jwkSetUri: ${authorization-server.issuerUri}/.well-known/jwks.json

spring:
  application:
    name: peacetrue-microservice-client-outer
  security:
    oauth2:
      client:
        provider:
          spring:
            #            issuerUri: ${authorization-server.issuerUri}
            jwkSetUri: ${authorization-server.jwkSetUri}
            authorization-uri: ${authorization-server.issuerUri}/oauth2/authorize
            token-uri: ${authorization-server.issuerUri}/oauth2/token
        registration:
          client-outter-authorization-code:
            provider: spring
            client-id: peacetrue
            client-secret: password
            authorization-grant-type: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: message.read,message.write
          client-outter-client-credentials:
            provider: spring
            client-id: peacetrue
            client-secret: password
            authorization-grant-type: client_credentials
            scope: message.read,message.write
    user:
      name: ${MICROSERVICE_SECURITY_USERNAME:peacetrue}
      password: ${MICROSERVICE_SECURITY_PASSWORD:password}

server.port: 8531

gateway:
  hostname: localhost
  url: ${MICROSERVICE_PROTOCOL:http}://${gateway.hostname}

#spring.profiles.include: uaa,rabbitmq
management.endpoints.web.exposure.include: "*"
# 默认禁用 zipkin
spring.zipkin.enabled: false

logging.level.root: DEBUG
#在项目内运行 java 的相对路径
#logging.config: file:peacetrue-microservice-common/logback-spring.xml

---
#默认环境
spring.profiles: default
spring.profiles.include: consoleLog

---

spring.profiles: prod
#spring.profiles.include: https,fileLog,rabbitmqLog,cmd,zipkin
spring.profiles.include: fileLog,rabbitmqLog,cmd,zipkin

gateway.hostname: peacetrue.cn
authorization-server.hostname: peacetrue.cn
spring.rabbitmq.host: peacetrue.cn
spring.zipkin.base-url: http://peacetrue.cn:9411/

logging.level.root: INFO

---

spring.profiles: https

MICROSERVICE_PROTOCOL: https

server:
  ssl:
    #服务端
    key-store: file://${user.home}/peacetrue.cn.jks
    key-alias: peacetrue.cn
    key-store-password: ${MICROSERVICE_SSL_PASSWORD:password}

authorization-server.port: 8443

---
#zipkin，默认禁用，激活此项以启用
spring.profiles: zipkin
spring.zipkin.enabled: true

---
#默认输出到控制台，激活此配置切换到文件
spring.profiles: fileLog

logging.file.name: logs/root.log

---
#命令行
spring.profiles: cmd

# 通过命令行启动会在模块内运行
#logging.config: file:../peacetrue-microservice-common/logback-spring.xml


---
#授权服务配置（UAA 完善的），默认使用 spring-security-oauth2，激活此配置使用 UAA
spring.profiles: uaa

authorization-server:
  port: 8080
  issuerUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}/uaa/oauth/token
  jwkSetUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}/uaa/token_keys


---
#消息总线通过 rabbitmq 发送消息
spring.profiles: rabbitmq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
