FROM adoptopenjdk:11-jdk-hotspot
#COPY libs/application-default.yml application-default.yml
#COPY libs/peacetrue-microservice-registry-center-1.0.0-SNAPSHOT.jar app.jar
#cd peacetrue-microservice-registry-center
#docker build -t peacetrue-microservice-registry-center .
#docker run --name peacetrue-microservice-registry-center -d -v /Users/xiayx/Documents/Projects/peacetrue-microservice/peacetrue-microservice-registry-center/logs:/log -p 8700:8700 peacetrue-microservice-registry-center
#docker exec -it peacetrue-microservice-registry-center bash
