= 项目介绍

本文主要讲解如何实现 link:index.adoc[安宁微服务^]。

== 项目地址

本项目源码放在 https://github.com/peacetrue/peacetrue-microservice-template[Github^] 上，可以检出后查看；如果想在本地运行，还需要检出与本项目配套的 https://github.com/peacetrue/peacetrue-microservice-template[远程仓库^]。

== 项目环境

* openjdk：13
* 源码级别、编译级别：9
* 构建工具：gradle 6.4
* spring-boot：2.3.0.RELEASE
* spring-security：5.3.2.RELEASE
* spring-cloud：2.2.2.RELEASE

== 项目模块

http 和 https 端口默认是相同的，不同的会单独说明。

peacetrue-microservice-config-center::
配置中心，监听在 8888 端口，关联 https://github.com/peacetrue/peacetrue-microservice-config-repo-template[peacetrue-microservice-config-repo-template^] 远程仓库。
peacetrue-microservice-registry-center::
注册中心，监听在 8761 端口，关联配置中心。
peacetrue-microservice-gateway::
接口网关，监听在 80（http） / 443（https）端口，关联配置中心和注册中心。
peacetrue-microservice-authorization-server::
认证中心，监听在 8510 端口，关联配置中心和注册中心。认证中心基于已过期的 https://projects.spring.io/spring-security-oauth/docs/Home.html[Spring Security OAuth2^] 项目，新项目 https://github.com/spring-projects-experimental/spring-authorization-server[spring-authorization-server^] 正在开发中，预计在 8 月份发布第一个版本，届时会迁移。
peacetrue-microservice-uaa::
认证中心，监听在 8080（http） / 8443（https）端口。因为 peacetrue-microservice-authorization-server 不支持授权码认证流程，所以实际使用该认证中心。
peacetrue-microservice-resource-server::
资源服务，监听在 8520 端口，关联配置中心、注册中心和认证中心，提供基于 JWT 的 OAuth2 访问令牌验证。包含两个接口：
. `GET /message`：需要 *message.read* 或 *message.write* 权限
. `POST /message`：需要 *message.write* 权限
peacetrue-microservice-client-inner::
内部客户端，供内部系统使用，监听在 8530 端口，关联配置中心、注册中心、认证中心和资源服务，提供基于 OAuth2 的授权码认证。
peacetrue-microservice-client-outer::
外部客户端，供第三方系统使用，监听在 8531 端口，关联接口网关和认证授权中心，提供基于 OAuth2 的客户端凭据认证。

== 配置规划

配置分为 2 部分：项目内配置和远程仓库配置。为了统一配置，尽可能使用远程仓库的配置。

配置中心只能使用项目内配置，不能使用远程仓库配置。所有其他项目都使用远程仓库配置，项目内只保留最基本的配置，包括应用名和远程仓库地址。

目前设计两套环境：开发环境（default）和生产环境（prod）。另外，还有一些局部环境包括：协议、日志、docker。协议包括：http 和 https；日志包括：控制台和文件；docker 包括 docker 内和非 docker。开发环境默认使用 http 协议、控制台日志和非 docker；生产环境默认使用 https 协议、文件日志和非 docker。上线前，需要在本地模拟生产环境，可手动切换为 https 协议，验证无误后部署上线。

docker 目前尚未实现，以下配置未实现 docker。

=== 配置中心配置

配置中心只有项目内配置。

.项目内配置
[source%nowrap,yml]
----
spring:
  application:
    #应用名
    name: peacetrue-microservice-config-center
  security:
    #访问配置中心的用户账号和密码
    user:
      name: ${MICROSERVICE_SECURITY_USERNAME:peacetrue}
      password: ${MICROSERVICE_SECURITY_PASSWORD:password}

server.port: ${MICROSERVICE_CONFIG_PORT:8888}
management.endpoints.web.exposure.include: "*"

---
#开发环境（默认环境）
spring.profiles: default
#使用本地文件存储配置需要激活 native
spring.profiles.active: native

spring:
  cloud:
    config:
      server:
        native:
          #直接使用本地文件，避免检出 github 仓库
          searchLocations: file:../peacetrue-microservice-config-repo-template

logging.level.org.springframework: debug
logging.level.com.github.peacetrue: debug

---
#生产环境
spring.profiles: prod
#默认激活 https 和 log
spring.profiles.active: https,log

spring:
  cloud:
    config:
      server:
        git:
          #远程资源库地址
          uri: https://github.com/peacetrue/peacetrue-microservice-config-repo-template
          #如果是私有仓库需要提供用户名和密码
          username: '${MICROSERVICE_REPO_USERNAME:peacetrue}'
          password: '${MICROSERVICE_REPO_PASSWORD:password}'

logging.level.org.springframework: info
logging.level.com.github.peacetrue: info

---
#默认 http 协议，激活此配置切换到 https 协议
spring.profiles: https

server:
  ssl:
    key-store: file://${user.home}/peacetrue.cn.jks
    key-alias: peacetrue.cn
    key-store-password: ${MICROSERVICE_SSL_PASSWORD:password}

---
#默认输出到控制台，激活此配置切换到文件
spring.profiles: log

logging.file.name: logs/root.log
----

=== 非配置中心配置

非配置中心配置包括项目内配置和远程仓库配置。

不同的应用，项目内配置除了应用名不同，其他都相同，因为它们都连接到同一个配置中心。

.项目内配置
[source%nowrap,yml]
----
spring:
  application:
    #应用名
    name: peacetrue-microservice-app
  cloud:
    config:
      #配置中心地址
      uri: ${MICROSERVICE_PROTOCOL:http}://${MICROSERVICE_SECURITY_USERNAME:peacetrue}:${MICROSERVICE_SECURITY_PASSWORD:password}@${MICROSERVICE_CONFIG_HOST:localhost}:${MICROSERVICE_CONFIG_PORT:8888}
      fail-fast: true

---
#生产环境
spring.profiles: prod
spring.profiles.include: https

MICROSERVICE_CONFIG_HOST: peacetrue.cn

---
#默认 http 协议，激活此配置切换到 https 协议
spring.profiles: https

MICROSERVICE_PROTOCOL: https
----

不同的应用，共用同一个远程仓库配置 `application.yml`，然后有一个自己单独的配置 `{应用名}.yml`，上例为：`peacetrue-microservice-app.yml`。

.远程仓库配置
[source%nowrap,yml]
----
#授权服务配置（spring-security-oauth2 过期不完善的）
authorization-server:
  hostname: localhost
  port: 8510
  issuerUri: ${MICROSERVICE_PROTOCOL:http}://${authorization-server.hostname}:${authorization-server.port}
  jwkSetUri: ${authorization-server.issuerUri}/.well-known/jwks.json

#所有应用共用的账号
spring:
  security:
    user:
      name: ${MICROSERVICE_SECURITY_USERNAME:peacetrue}
      password: ${MICROSERVICE_SECURITY_PASSWORD:password}

#注册客户端配置
eureka:
  instance:
    #优先使用 host 访问而非 ip 地址
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${MICROSERVICE_PROTOCOL:http}://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka

management.endpoints.web.exposure.include: "*"

---
#开发环境（默认环境）
spring.profiles: default

logging.level.org.springframework: debug
logging.level.com.github.peacetrue: debug

---
#生产环境
spring.profiles: prod
spring.profiles.include: https,log

eureka.instance.hostname: peacetrue.cn

db.hostname: peacetrue.cn

logging.level.org.springframework: info
logging.level.com.github.peacetrue: info

---
#默认 http 协议，激活此配置切换到 https 协议
spring.profiles: https

MICROSERVICE_PROTOCOL: https

server:
  ssl:
    #服务端
    key-store: file://${user.home}/peacetrue.cn.jks
    key-alias: peacetrue.cn
    key-store-password: ${MICROSERVICE_SSL_PASSWORD:password}

eureka.instance.securePortEnabled: true

---
#默认输出到控制台，激活此配置切换到文件
spring.profiles: log

logging.file.name: logs/root.log

---
#资源服务配置
spring.profiles: resourceserver

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: ${authorization-server.issuerUri}
          jwkSetUri: ${authorization-server.jwkSetUri}

---
#认证客户端配置
spring.profiles: authorizationclient

spring:
  security:
    oauth2:
      client:
        provider:
          peacetrue:
            issuerUri: ${authorization-server.issuerUri}
            jwkSetUri: ${authorization-server.jwkSetUri}
        peacetrue:
          provider: peacetrue
          redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'

---
#授权服务配置（UAA 完善的），默认使用 spring-security-oauth2，激活此配置使用 UAA
spring.profiles: uaa

authorization-server:
  port: 8080
  issuerUri: http://${authorization-server.hostname}:${authorization-server.port}/uaa/oauth/token
  jwkSetUri: http://${authorization-server.hostname}:${authorization-server.port}/uaa/token_keys
----

== 初始配置

系统中所有涉及到的用户名和密码都默认为：peacetrue / password。为了方便配置提供了一些特殊变量：

* 配置中心变量：配置中心变量影响所有项目，所以提供一种统一配置方式
* 账号密码变量：私密信息可以不暴露在配置文件中

配置中心变量::
通过以下命令添加到系统环境：
* 主机名：`export MICROSERVICE_CONFIG_HOST=localhost`
* 端口：`export MICROSERVICE_CONFIG_PORT=8888`

远程仓库账号::
如果是私有仓库，需要提供账号密码，通过以下命令添加到系统环境：
* export MICROSERVICE_REPO_USERNAME=peacetrue
* export MICROSERVICE_REPO_PASSWORD=password

安全认证账号::
通过以下命令添加到系统环境：
* export MICROSERVICE_SECURITY_USERNAME=peacetrue
* export MICROSERVICE_SECURITY_PASSWORD=password

SSL账号::
* export MICROSERVICE_SSL_PASSWORD=password

数据库::
* export MICROSERVICE_DB_USERNAME=peacetrue
* export MICROSERVICE_DB_PASSWORD=password
