FROM adoptopenjdk:11-jdk-hotspot
#COPY libs/peacetrue-microservice-config-center-1.0.0-SNAPSHOT.jar app.jar
#docker build -t peacetrue-microservice-config-center .
#docker run --name peacetrue-microservice-config-center -d -v /Users/xiayx/Documents/Projects/peacetrue-microservice/peacetrue-microservice-config-center/logs:/log -p 8710:8710 peacetrue-microservice-config-center
#docker exec -it peacetrue-microservice-config-center bash
